models.py
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.sql import func 
from flask_login import UserMixin 

db = SQLAlchemy()

class User(db.Model,UserMixin):
	id  = db.Column(db.Integer, primary_key=True)
	email = db.Column(db.String(150),unique=True)
	username = db.Column(db.String(150),unique=True)
	password = db.Column(db.String(150))
	date_created = db.Column(db.DateTime(timezone=True), default=func.now())
	posts = db.relationship('Post',backref='user', passive_deletes=True)
	comments = db.relationship('Comment',backref='user', passive_deletes=True)
	likes = db.relationship('Like',backref='user', passive_deletes=True)




class Post(db.Model):
	id  = db.Column(db.Integer, primary_key=True)
	text= db.Column(db.Text, nullable=False)
	date_created = db.Column(db.DateTime(timezone=True), default=func.now())
	author = db.Column(db.Integer,db.ForeignKey('user.id', ondelete ="CASCADE"), nullable=False)
	comments = db.relationship('Comment',backref='post', passive_deletes=True)
	likes = db.relationship('Like',backref='post', passive_deletes=True)



class Comment(db.Model):
	id  = db.Column(db.Integer, primary_key=True)
	text= db.Column(db.String(200), nullable=False)
	date_created = db.Column(db.DateTime(timezone=True), default=func.now())
	author = db.Column(db.Integer,db.ForeignKey('user.id', ondelete ="CASCADE"), nullable=False)
	post_id = db.Column(db.Integer,db.ForeignKey('post.id', ondelete ="CASCADE"), nullable=False)


class Like(db.Model):
	id  = db.Column(db.Integer, primary_key=True)
	date_created = db.Column(db.DateTime(timezone=True), default=func.now())
	author = db.Column(db.Integer,db.ForeignKey('user.id', ondelete ="CASCADE"), nullable=False)
	post_id = db.Column(db.Integer,db.ForeignKey('post.id', ondelete ="CASCADE"), nullable=False)

auth.py
from flask import Blueprint,render_template,url_for,redirect,request,flash
from flask_login import login_user,logout_user,login_required,current_user
from models import User,db
from views import views
from werkzeug.security import generate_password_hash,check_password_hash

auth = Blueprint("auth",__name__)



@auth.route("/login", methods=['GET','POST'])
def login():
    if request.method =='POST':
        email = request.form.get("email")
        password = request.form.get("password")

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password,password):
                flash("Logged in!",category='success')
                login_user(user,remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Password is incorrect.',category='error')
        else:
            flash('Email does not exists.',category='error')


    return render_template("login.html", user = current_user)

@auth.route("/sign-up", methods=['GET','POST'])
def sign_up():
    if request.method =='POST':
        email = request.form.get("email")
        username = request.form.get("username")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")
        
        email_exists = User.query.filter_by(email=email).first()
        username_exists = User.query.filter_by(username=username).first()
        
        if email_exists:
            flash('Email is already in use.',category='error')
        elif username_exists:
            flash('username is already in use.',category='error')
        elif password1 != password2:
            flash('Password don\'t matrch!',category='error')
        elif len(username)< 2:
            flash('Username is too short.',category='error')
        elif len(password1)< 6:
            flash('password1 is too short.',category='error')
        elif len(email) < 10:
            flash("Email is invalid.",category='error')
        else:
            new_user = User(email=email,username=username,password=generate_password_hash (password1,method='pbkdf2:sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user,remember=True)
            flash('User created!', category='success')
            return redirect(url_for('views.home'))
    
    return render_template("signup.html",user = current_user)
    

@auth.route("/logout")
@login_required
def logout():
    logout_user()

    return redirect(url_for("views.home"))

main.py
from flask import Flask,render_template,redirect,url_for,Blueprint
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.sql import func
from views import views
from auth import auth
from models import User, db,Post,Comment,Like
from flask_login import LoginManager



app = Flask(__name__)
app.config['SECRET_KEY'] = "helloworld"
app.config['SQLALCHEMY_DATABASE_URI'] ="sqlite:///Blogpost.db"
app.app_context().push()
db.init_app(app)


app.register_blueprint(auth, url_prefix="/")
app.register_blueprint(views, url_prefix="/")

login_manager = LoginManager()
login_manager.login_view = "auth.login"
login_manager.init_app(app)

@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))


@app.route("/")
def home():
    return "<h1>Home</h1>"

@app.route("/profile")
def profile():
    return "<h1>profile</h1>"

if __name__ == "__main__":
    app.run(debug=True)
db.create_all()

views.py
from flask import Blueprint,render_template ,request,flash,redirect,url_for
from flask_login import login_user,logout_user,login_required,current_user
from models import Post,db,User,Comment,Like


views = Blueprint("views",__name__)


@views.route("/")
@views.route("/home")
@login_required
def home():
    posts = Post.query.all()
    return render_template ("home.html",user = current_user, posts=posts)

@views.route("/create-post", methods =['GET','POST'])
@login_required
def create_post():
    if request.method == "POST":
        text = request.form.get('text')

        if not text:
            flash('Post cannot be empty', category='error')

        else:
            post=Post(text=text, author= current_user.id)
            db.session.add(post)
            db.session.commit()
            flash('Post created!',category='success')
            
            return redirect(url_for('views.home'))

    return render_template ("create_post.html",user= current_user )

@views.route("/delete-post/<id>")
@login_required
def delete_post(id):
    posts =Post.query.filter_by(id=id).first()

    if not posts:
        flash("post does not exist.", category='error')
    elif current_user.id != posts.author:
        flash('you do not have permission to delete this post.')
    else:
        db.session.delete(posts)
        db.session.commit()
        flash('post deleted!', category='success')

    return redirect(url_for('views.home'))

@views.route("/posts/<username>")
@login_required
def posts(username):
    user=User.query.filter_by(username=username).first()
    if not user:
        flash('No user with that username exist.',category='error')
        return redirect(url_for('views.home'))
    posts =user.posts
    return render_template("posts.html", user=current_user, posts=posts, username=username)


@views.route("/create-comment/<post_id>", methods=['GET', 'POST'])
@login_required
def create_comment(post_id):
    text = request.form.get('text')

    if not text:
        flash('Comment cannot be empty.', category='error')
    else:
        post = Post.query.filter_by(id=post_id)
        if post:
            comment = Comment(
                text=text, author=current_user.id, post_id=post_id)
            db.session.add(comment)
            db.session.commit()
        else:
            flash('Post does not exist.', category='error')

    return redirect(url_for('views.home'))



@views.route("/delete-comment/<comment_id>")
@login_required
def delete_comment(comment_id):
    comment = Comment.query.filter_by(id=comment_id).first()

    if not comment:
        flash('Comment does not exist.', category='error')

    elif current_user.id != comment.author and current_user.id != comment.post.author :
        flash('You do not have permission to delete this comment', category='error')

    else:
        db.session.delete(comment)
        db.session.commit()

        
    return redirect (url_for('views.home'))

@views.route("/like-post/<post_id>", methods=['GET'])
@login_required
def like(post_id):
    post= Post.query.filter_by(id=post_id)
    like= Like.query.filter_by(author = current_user.id,post_id = post_id).first()

    if not post:
        flash('Post does not exist.',category='error')
    elif like:
        db.session.delete(like)
        db.session.commit()
    else:
        like=Like(author = current_user.id, post_id = post_id)
        db.session.add(like)
        db.session.commit()
    return redirect(url_for('views.home'))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
    <script src="https://kit.fontawesome.com/8b1ceb75ab.js" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="/home">Home</a>></a>
                    <a class="nav-item nav-link {% if 'posts' in request.path %}active{% endif %}"
                        href="{{ url_for('views.posts', username=current_user.username) }}">My Posts</a>

                    {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="/logout">LogOut</a>></a>
                    {% else %}
                    <a class="nav-item nav-link" href="/login">Login</a>></a>
                    <a class="nav-item nav-link" href="/sign-up">SignUp</a>></a>

                    {% endif %}
                    {% if user.is_authenticated %}
                    <span class="navbar-text ms-auto">
                        Welcome, {{ user.username }}
                    </span>
                    {% endif %}

                </div>
            </div>
        </div>
    </nav>
    <div class="container">{%block content %}{% endblock %}</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous">
    </script>
</body>

</html>

templates/create_post.html
{% extends "base.html"%} {% block title %}Home{% endblock %}
{% block content %}
<h1 align="center">Make a Post</h1>

<form method = 'POST'>
    <textarea name="text" id="text" class="form-control"></textarea>
    <br/>
    <div align="center">
    <button type="submit" class="btn btn-lg btn-primary">Post</button>
    </div>

</form>
<br/>
<div align="center">
<a href="/home"><button type="button" class="btn btn-lg btn-secondary">Back</button></a>
</div>
{% endblock %}

templates/home.html
{% extends "posts_div.html"%} {% block title %}Home{% endblock %}

templates/login.html
{% extends "base.html"%}{% block title %}Login{% endblock %}{% block content
    %}
    <form method="POST">
        <h3 align="center">Login</h3>
        <div class="form-group">
            <label for="email">Email Address</label>
            <input
              type="text"
              id="email"
              name="email"
              class="form-control"
              placeholder="Enter Email"
            />
            <label for="password">Password </label>
            <input
              type="password"
              id="password"
              name="password"
              class="form-control"
              placeholder="Enter password"
            />
            <br/>
            <div align="center">
                <button class="btn btn-primary"type="submit">Login</button>
            </div>
        </div>   
    </form>
     

{% endblock %}

templates/posts.html
{% extends "posts_div.html"%}{% block title %}{{username}}'s posts{% endblock %}
{% block header %} {{username}}'s posts {% 
    endblock %}{% block footer %}
    <div align="center">
        <a href="/home"><button type="button" class="btn btn-primary btn-lg">
            Back</button></a
        >
    </div>
    {% endblock %}

templates/posts_div.html
{% extends "base.html"%}{% block title %}Home{% endblock %}
{% block content %}
<h1 align="center">{% block header %}Posts{% endblock %}</h1>
<div id="posts">
    {% for post in posts %}
    <div class="card border-dark">
        <div class="card-header d-flex justify-content-between align-items-center">
            <a href="/posts/{{post.user.username}}">{{post.user.username}}</a>
            <div>
                {{post.likes|length}}
                {% if user.id in post.likes|map(attribute="author")|list %}
                <a href="/like-post/{{post.id}}"><i class="fa-solid fa-thumbs-up"></i></a>
                {% else %}
                <a href="/like-post/{{post.id}}"><i class="fa-regular fa-thumbs-up"></i></a>
                {% endif %}
                
                {% if user.id == post.author %}
                <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-primary dropdown-toggle"data-bs-toggle="dropdown">
                    </button>
                    <ul class="dropdown-menu">
                        <li><a href="/delete-post/{{post.id}}" class="dropdown-item">Delete</a></li>
                    </ul>
    
                </div>
                {% endif %}
            
            </div>
            
        </div>
        <div class="card-body">
            <div class="card-text">{{post.text}}</div>
            <br />
            <div class="collapse" id="comments-{{post.id}}">
                <div class="card">
                    <div class="card-body" id="comments-expanded-{{post.id}}">
                        {% for comment in post.comments %}
                        <div class="d-flex justify-content-between align-items-center">
                            <div>
                               <a href="/posts/{{comment.user.username}}">{{comment.user.username}}</a>:{{comment.text}}
                               
                            </div>
                            <div>
                                <small class="text-muted">{{comment.date_created}}
                                </small>
                                {% if user.id == comment.author or user.id == post.author%}
                                <div class="btn-group">
                                    <button type="button" class="btn btn-sm btn-primary dropdown-toggle"data-bs-toggle="dropdown">
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li><a href="/delete-comment/{{comment.id}}" class="dropdown-item">Delete</a></li>
                                    </ul>
                    
                                </div>
                                {% endif %}
                            </div>
                        </div>
                        {% endfor %}
                    </div> 
                </div>    
            </div>
            <p class="card-text">
                {% if post.comments|length > 0 %}
                <a data-bs-toggle="collapse" href="#comments-{{post.id}}" role="button">
                    <small>View {{post.comments|length}} Comments</small>
                </a>
                {% else %}
                <small class="text-muted">No Comments</small>
                {% endif %}
            </p>
            <form class="input-group mb-3" method='POST' action="/create-comment/{{post.id}}">
                <input type="text" id="text" name="text" class="form-control" placeholder="comment something!" />
                <button type="submit" class="btn btn-primary">Comment</button>
            </form>
        </div>
        <div class="card-footer text-muted">{{post.date_created}}</div>
    </div>
    
    </br >{% endfor %}        
                    

</div>
{% block footer %}
<div align="center">
    <a href="/create-post"><button type="button" class="btn btn-primary btn-lg">
        Create a post</button></a>
</div>
{% endblock %}{% endblock %}

templates/signup.html
{% extends "base.html"%}{% block title %}Sign Up{% endblock %}{% block content 
    %}
    <form method="POST">
        <h3 align="center">Sign Up</h3>
        <div class="form-group">
            <label for="email">Email Address</label>
            <input
              type="text"
              id="email"
              name="email"
              class="form-control"
              placeholder="Enter Email"
            />
            <label for="Username">Username</label>
            <input
              type="text"
              id="Username"
              name="username"
              class="form-control"
              placeholder="Enter Username"
            />
            <label for="password1">password</label>
            <input
              type="password"
              id="password1"
              name="password1"
              class="form-control"
              placeholder="Enter password"
            />
            <label for="password2">password again</label>
            <input
              type="password"
              id="password2"
              name="password2"
              class="form-control"
              placeholder="Enter password Again"
            />
            <br/>
            <div align="center">
               <button class="btn btn-primary"type="submit">Sign Up</button>
            </div>
        </div>   
    </form>


{% endblock %}